const skillTrees = [
  {
    name: 'Algorithm Mastery',
    description: 'Master fundamental algorithms from basics to advanced',
    icon: '🧮',
    color: '#6c5ce7',
    nodes: [
      { nodeId: 'algo-basics', title: 'Algorithm Basics', description: 'Arrays, strings, and basic loops', xpRequired: 0, position: { x: 250, y: 50 }, connections: ['algo-search', 'algo-sort'], tier: 1 },
      { nodeId: 'algo-search', title: 'Searching', description: 'Binary search, linear search', xpRequired: 100, position: { x: 150, y: 150 }, connections: ['algo-recursion'], tier: 2 },
      { nodeId: 'algo-sort', title: 'Sorting', description: 'Quick sort, merge sort, bubble sort', xpRequired: 100, position: { x: 350, y: 150 }, connections: ['algo-recursion'], tier: 2 },
      { nodeId: 'algo-recursion', title: 'Recursion', description: 'Recursive thinking and backtracking', xpRequired: 200, position: { x: 250, y: 250 }, connections: ['algo-dp', 'algo-graphs'], tier: 3 },
      { nodeId: 'algo-dp', title: 'Dynamic Programming', description: 'Memoization and tabulation', xpRequired: 400, position: { x: 150, y: 350 }, connections: ['algo-master'], tier: 4 },
      { nodeId: 'algo-graphs', title: 'Graph Algorithms', description: 'BFS, DFS, shortest path', xpRequired: 400, position: { x: 350, y: 350 }, connections: ['algo-master'], tier: 4 },
      { nodeId: 'algo-master', title: 'Algorithm Expert', description: 'Advanced problem-solving', xpRequired: 800, position: { x: 250, y: 450 }, connections: [], tier: 5 },
    ],
  },
  {
    name: 'Frontend Engineering',
    description: 'Build modern user interfaces and web applications',
    icon: '🎨',
    color: '#00cec9',
    nodes: [
      {
        nodeId: 'fe-html',
        title: 'HTML & CSS',
        description: 'Semantic HTML, Accessible Forms, ARIA, Meta Tags, CSS Box Model, Specificity, Units & Colors, Flexbox, CSS Grid, Transitions, Keyframe Animations, UI Component Styling (Button, Card, Modal, Accordion, Tooltip, Dropdown, Tabs)',
        xpRequired: 0,
        position: { x: 250, y: 50 },
        connections: ['fe-js', 'fe-responsive'],
        tier: 1,
        topics: [
          'HTML Document Structure',
          'Semantic HTML',
          'Accessible Forms',
          'ARIA Basics',
          'Data Attributes',
          'Meta Tags & OpenGraph',
          'Tables & Data Grids',
          'CSS Specificity & Cascade',
          'Box Model & Sizing',
          'CSS Units (px, rem, em, %, vh, vw)',
          'Color Models (HEX, RGB, HSL)',
          'Z-Index & Stacking Context',
          'Flexbox: Justify Content & Alignment',
          'Flexbox: Flex Grow, Shrink & Basis',
          'CSS Grid Fundamentals',
          'Keyframe Animations',
          'Typography & Font Loading',
          'Shadows & Elevation',
          'CSS Variables & Custom Properties',
          'Responsive Images & Aspect Ratio',
          'CSS Transitions & Timing Functions',
          'Button Component Styling',
          'Navigation Bar Layout',
          'Card Component Layout',
          'Modal Dialog Overlay',
          'Hero Section Layout',
          'Badge Component',
          'Tooltip Component',
          'Dropdown Menu',
          'Accordion Component',
          'Alert & Toast Notification',
          'Tabs Component',
          'Avatar Component',
          'Progress Bar',
          'Breadcrumb Navigation'
        ]
      },
      {
        nodeId: 'fe-js',
        title: 'JavaScript',
        description: 'ES6+ JavaScript, Arrays and Objects Transformation, Deep Clone, Closures, Currying, Event Delegation, DOM Manipulation, Debounce & Throttle, Promises, Async/Await, Microtasks, Regular Expressions',
        xpRequired: 100,
        position: { x: 150, y: 150 },
        connections: ['fe-react'],
        tier: 2,
        topics: [
          'Arrays and Objects',
          'Array Transformations (map, filter, reduce)',
          'Deep Clone & Object Immutability',
          'Object Property Inversion',
          'Object Path Getter',
          'Array Chunking',
          'Unique Array by Key',
          'Group Array by Attribute',
          'Array Flattening with Depth',
          'Memoization Cache Function',
          'DOM & Browser',
          'Event Delegation',
          'Debounce Utility',
          'Throttle Utility',
          'DOM Class Toggle & Manipulation',
          'Virtual DOM Element Builder',
          'Query Selector Element Matcher',
          'Form Serializer',
          'Cookie Parser',
          'LocalStorage Wrapper',
          'URL Search Params Parser',
          'Asynchronous JavaScript',
          'Promise.all Concurrency',
          'Promise.race First Settled',
          'Async Retry with Backoff',
          'Sequential Async Execution',
          'Polling Utility with Timeout',
          'Promise Timeout Wrapper',
          'Node-style Promisify',
          'Async Queue Concurrency Limiter',
          'Functions & Closures',
          'Function Currying',
          'Function Composition (pipe/compose)',
          'Once Function Execution',
          'JavaScript Fundamentals & Scope',
          'Type Coercion & Strict Equality',
          'Regular Expressions Validation',
          'Phone Number & Input Formatting'
        ]
      },
      {
        nodeId: 'fe-responsive',
        title: 'Responsive Design',
        description: 'Media Queries, Breakpoints, Fluid Typography, clamp(), Viewport Units, Container Queries, Touch Interfaces, Responsive Images (srcset), Mobile Navigation, Responsive Layouts',
        xpRequired: 100,
        position: { x: 350, y: 150 },
        connections: ['fe-react'],
        tier: 2,
        topics: [
          'Breakpoints & Media Queries',
          'clamp() Fluid Scaling',
          'Viewport Units (vw, vh, vmin, vmax)',
          'Responsive Typography & Scaling',
          'Container Queries',
          'Touch-Friendly Interfaces & Tap Targets',
          'Responsive Images with srcset',
          'Picture Element Art Direction',
          'Device Orientation Detection',
          'Flexbox Responsive Wrapping',
          'Responsive Card Grid',
          'Responsive Navbar & Header',
          'Mobile Hamburger Menu',
          'Responsive Pricing Table',
          'Responsive Multi-Column Footer',
          'Responsive Dashboard Grid',
          'Responsive Modal Dialog',
          'Responsive Product Card',
          'Responsive Split Screen Layout',
          'Responsive Form Layout',
          'Responsive Tables & Card Conversion',
          'Fluid Typographic Scale',
          'min() and max() Clamp Calculation',
          'Responsive Container System',
          'Responsive Tabbed Navigation'
        ]
      },
      {
        nodeId: 'fe-react',
        title: 'React',
        description: 'React Components, useState, useEffect, Custom Hooks, Context API, Error Boundaries, React Router, Controlled Components, useRef, useMemo, Reconciliation, State Lifting',
        xpRequired: 200,
        position: { x: 250, y: 250 },
        connections: ['fe-advanced', 'fe-testing'],
        tier: 3,
        topics: [
          'useState State Container',
          'useEffect Dependency & Cleanup Tracker',
          'React Router Path Parser',
          'Optimistic UI State Updater',
          'Context API Provider/Consumer',
          'Error Boundary State Tracker',
          'Counter with Step & Limits',
          'Toggle Hook State',
          'Input Mirror & Controlled Forms',
          'Character Counter with Max Limit',
          'Star Rating Component',
          'Accordion Controller State',
          'Tab Switcher Component',
          'Modal State Machine',
          'Protected Routes & Auth Guard',
          'Pagination Controller',
          'Filterable Product List',
          'Reconciliation & Key Strategy',
          'Controlled vs Uncontrolled Components',
          'Lifting State Up',
          'useRef Focus & Value Tracker',
          'useMemo Computation Cache',
          'Lists and Keys Reorderer',
          'Custom useLocalStorage Hook',
          'React Portals Simulation',
          'Search Bar with Clear Action',
          'Multi-Select Checkbox Group',
          'Stepper & Multi-Step Wizard',
          'Component Composition Pattern',
          'Loading State Skeleton Controller',
          'Drag & Drop Item Reorderer',
          'Notification Toast Queue'
        ]
      },
      {
        nodeId: 'fe-advanced',
        title: 'Advanced React',
        description: 'Compound Components, HOCs, Render Props, React Fiber, Suspense, Concurrent Mode, React Query, Virtualization, Code Splitting, Micro Frontends, Performance Profiling',
        xpRequired: 400,
        position: { x: 150, y: 350 },
        connections: ['fe-master'],
        tier: 4,
        topics: [
          'Compound Components State Sharing',
          'Higher-Order Components (HOC)',
          'Render Props Pattern',
          'Headless Components State Reducer',
          'Custom Hook Composition (usePrevious)',
          'Custom Hook Composition (useDebouncedValue)',
          'Custom Hook Composition (useOnlineStatus)',
          'React.memo Memoization Comparator',
          'Code Splitting & Dynamic Imports',
          'React Fiber Architecture',
          'Suspense for Data Fetching',
          'Concurrent Rendering & useTransition',
          'Hydration Error Detection',
          'React Query: Stale-While-Revalidate',
          'React Query: Cache Invalidation',
          'Virtualized List Windowing',
          'Infinite Scroll Sentinel Observer',
          'Resizable Split Panel Layout',
          'Redux State Reducer & Action Dispatcher',
          'Micro Frontends Module Federation',
          'Design System Theme Provider',
          'React Performance Profiler',
          'Server-Driven UI Component Parser',
          'Dynamic Schema Form Builder',
          'Animated Page Transition Coordinator'
        ]
      },
      {
        nodeId: 'fe-testing',
        title: 'Testing',
        description: 'Testing Fundamentals, Unit Testing, Component Testing, Mocking & Spies, Flaky Tests, Test Coverage, Accessibility Testing, Integration Tests, E2E Testing, TDD',
        xpRequired: 400,
        position: { x: 350, y: 350 },
        connections: ['fe-master'],
        tier: 4,
        topics: [
          'Testing Fundamentals & Assertions',
          'Mock Functions & Spies',
          'Test Coverage Calculation',
          'Flaky Test Detection & Mitigation',
          'Accessibility (a11y) Assertions',
          'Component Render Test Assertion',
          'Event Click Handler Assertion',
          'Async Data Fetch Testing',
          'Form Input & Validation Testing',
          'Snapshot Testing Serializer',
          'Custom Matchers Extension',
          'Hook Testing Harness (renderHook)',
          'Error Boundary Testing',
          'Mocking Fetch / API Client',
          'Integration Flow Test',
          'Mocking LocalStorage in Tests',
          'Testing Timers & Fake Timers',
          'Context Provider Test Harness',
          'Keyboard Navigation A11y Testing',
          'ARIA Role Assertion',
          'Visual Regression Testing',
          'Test-Driven Development (TDD)',
          'Testing User Interactions',
          'Test Fixtures Factory',
          'End-to-End (E2E) Test Runner'
        ]
      },
      {
        nodeId: 'fe-master',
        title: 'Frontend Expert',
        description: 'Core Web Vitals, Critical Rendering Path, Memory Management, Service Workers, Web Workers, Security (XSS/CSRF/CSP), Monorepos, i18n, Real-Time WebSockets, High-Performance Canvas',
        xpRequired: 800,
        position: { x: 250, y: 450 },
        connections: [],
        tier: 5,
        topics: [
          'Core Web Vitals (LCP, FID/INP, CLS)',
          'Critical Rendering Path Optimization',
          'Memory Management & Leak Detection',
          'Tree Shaking & Bundle Analysis',
          'Service Workers & Offline PWA',
          'Web Workers Off-Thread Computation',
          'Offline Synchronization Engine',
          'Micro Frontends Runtime Orchestrator',
          'Design System Multi-Theme Token Engine',
          'Multi-Tenant Frontend Architecture',
          'Real-Time Frontend Architecture (WebSocket)',
          'Frontend Security: XSS & CSP Defense',
          'Frontend Security: CSRF & Token Auth',
          'Monorepos & Workspace Dependency Graph',
          'Internationalization (i18n) Engine',
          'Web Accessibility (WCAG 2.1 AA/AAA)',
          'A/B Testing Feature Flag Engine',
          'Frontend Observability & Error Tracking',
          'Infinite Canvas / Whiteboard Engine',
          'Real-Time Collaborative Document',
          'Full-Featured Rich Text Editor State',
          'High-Performance Data Grid',
          'Interactive Chart Engine',
          'Video Player Custom Controls',
          'Client-Side Image Processing & Compression'
        ]
      },
    ],
  },
  {
    name: 'Backend Engineering',
    description: 'Build scalable server-side applications and APIs',
    icon: '⚙️',
    color: '#00b894',
    nodes: [
      {
        nodeId: 'be-node',
        title: 'Node.js Basics',
        description: 'JavaScript for Backend, Node.js Fundamentals, Modules, npm, File System, Events, HTTP, Async/Await, Streams, Error Handling',
        xpRequired: 0,
        position: { x: 250, y: 50 },
        connections: ['be-express', 'be-db'],
        tier: 1,
        topics: [
          'JavaScript for Backend',
          'Node.js Fundamentals',
          'Modules',
          'npm',
          'File System',
          'Events',
          'HTTP',
          'Asynchronous Programming',
          'Promises',
          'Async/Await',
          'Streams',
          'Error Handling'
        ]
      },
      {
        nodeId: 'be-express',
        title: 'Express.js',
        description: 'Express Fundamentals, Routing, Middleware, Request / Response, REST APIs, Controllers, Error Handling, Validation, API Design',
        xpRequired: 100,
        position: { x: 150, y: 150 },
        connections: ['be-auth'],
        tier: 2,
        topics: [
          'Express Fundamentals',
          'Routing',
          'Middleware',
          'Request / Response',
          'REST APIs',
          'Controllers',
          'Error Handling',
          'Validation',
          'API Design'
        ]
      },
      {
        nodeId: 'be-db',
        title: 'Databases',
        description: 'SQL Basics, PostgreSQL / MySQL, MongoDB, CRUD, Relationships, Joins, Indexing, Transactions, Database Design, ORM / ODM',
        xpRequired: 100,
        position: { x: 350, y: 150 },
        connections: ['be-auth'],
        tier: 2,
        topics: [
          'SQL Basics',
          'PostgreSQL / MySQL',
          'MongoDB',
          'CRUD',
          'Relationships',
          'Joins',
          'Indexing',
          'Transactions',
          'Database Design',
          'ORM / ODM'
        ]
      },
      {
        nodeId: 'be-auth',
        title: 'Authentication',
        description: 'Authentication vs Authorization, Password Hashing, Sessions, JWT, Cookies, Refresh Tokens, OAuth, Role-Based Access Control, Security, API Protection',
        xpRequired: 200,
        position: { x: 250, y: 250 },
        connections: ['be-scale', 'be-realtime'],
        tier: 3,
        topics: [
          'Authentication vs Authorization',
          'Password Hashing',
          'Sessions',
          'JWT',
          'Cookies',
          'Refresh Tokens',
          'OAuth',
          'Role-Based Access Control',
          'Security',
          'API Protection'
        ]
      },
      {
        nodeId: 'be-scale',
        title: 'Scaling',
        description: 'Caching, Redis, Load Balancing, Horizontal Scaling, Vertical Scaling, Database Optimization, Connection Pooling, Queues, Background Jobs, Microservices, Docker, Monitoring',
        xpRequired: 400,
        position: { x: 150, y: 350 },
        connections: ['be-master'],
        tier: 4,
        topics: [
          'Caching',
          'Redis',
          'Load Balancing',
          'Horizontal Scaling',
          'Vertical Scaling',
          'Database Optimization',
          'Connection Pooling',
          'Queues',
          'Background Jobs',
          'Microservices',
          'Docker',
          'Monitoring'
        ]
      },
      {
        nodeId: 'be-realtime',
        title: 'Real-time',
        description: 'WebSockets, Socket.IO, Server-Sent Events, Real-time Notifications, Chat Systems, Presence, Rooms, Pub/Sub, Event-Driven Architecture',
        xpRequired: 400,
        position: { x: 350, y: 350 },
        connections: ['be-master'],
        tier: 4,
        topics: [
          'WebSockets',
          'Socket.IO',
          'Server-Sent Events',
          'Real-time Notifications',
          'Chat Systems',
          'Presence',
          'Rooms',
          'Pub/Sub',
          'Event-Driven Architecture'
        ]
      },
      {
        nodeId: 'be-master',
        title: 'Backend Expert',
        description: 'System Design, Distributed Systems, Microservices, Event-Driven Architecture, Message Queues, Distributed Caching, Database Scaling, High Availability, Fault Tolerance, Observability, Security, Performance Engineering',
        xpRequired: 800,
        position: { x: 250, y: 450 },
        connections: [],
        tier: 5,
        topics: [
          'System Design',
          'Distributed Systems',
          'Microservices',
          'Event-Driven Architecture',
          'Message Queues',
          'Distributed Caching',
          'Database Scaling',
          'High Availability',
          'Fault Tolerance',
          'Observability',
          'Security',
          'Performance Engineering'
        ]
      },
    ],
  },
  {
    name: 'System Design',
    description: 'Design large-scale distributed systems',
    icon: '🏗️',
    color: '#fdcb6e',
    nodes: [
      {
        nodeId: 'sd-basics',
        title: 'Fundamentals',
        description: 'Core building blocks: scalability, availability, capacity estimation, API design, caching, and fundamental trade-offs.',
        xpRequired: 0,
        position: { x: 250, y: 50 },
        connections: ['sd-storage', 'sd-compute'],
        tier: 1,
        topics: [
          'What is System Design?',
          'Functional Requirements',
          'Non-Functional Requirements',
          'Scalability',
          'Availability',
          'Reliability',
          'Performance',
          'Latency',
          'Throughput',
          'Capacity Estimation',
          'Back-of-the-Envelope Calculations',
          'Horizontal Scaling',
          'Vertical Scaling',
          'Load Balancing',
          'Stateless vs Stateful Services',
          'API Design',
          'REST APIs',
          'RPC',
          'HTTP Basics',
          'WebSockets',
          'Authentication',
          'Authorization',
          'Rate Limiting',
          'Caching Basics',
          'CAP Theorem',
          'Consistency Models',
          'ACID',
          'BASE',
          'Idempotency',
          'Fault Tolerance'
        ]
      },
      {
        nodeId: 'sd-storage',
        title: 'Storage Systems',
        description: 'Relational and NoSQL databases, sharding, replication, consistent hashing, caching patterns, object stores, and data lakes.',
        xpRequired: 200,
        position: { x: 150, y: 150 },
        connections: ['sd-distributed'],
        tier: 2,
        topics: [
          'Relational Databases',
          'SQL',
          'NoSQL',
          'Key-Value Stores',
          'Document Databases',
          'Wide-Column Databases',
          'Graph Databases',
          'Database Indexing',
          'Composite Indexes',
          'Query Optimization',
          'Database Transactions',
          'Database Replication',
          'Primary-Replica Architecture',
          'Read Replicas',
          'Database Sharding',
          'Database Partitioning',
          'Consistent Hashing',
          'Hot Partitions',
          'Database Failover',
          'Connection Pooling',
          'Caching',
          'Cache-Aside',
          'Write-Through Cache',
          'Write-Behind Cache',
          'Cache Invalidation',
          'Distributed Cache',
          'Object Storage',
          'Blob Storage',
          'Data Warehouses',
          'Data Lakes'
        ]
      },
      {
        nodeId: 'sd-compute',
        title: 'Compute',
        description: 'Web servers, reverse proxies, microservices, containerization, Kubernetes, autoscaling, background workers, and resilient deployments.',
        xpRequired: 200,
        position: { x: 350, y: 150 },
        connections: ['sd-distributed'],
        tier: 2,
        topics: [
          'Web Servers',
          'Application Servers',
          'Load Balancers',
          'Reverse Proxies',
          'API Gateways',
          'Monolith Architecture',
          'Microservices',
          'Service-Oriented Architecture',
          'Containerization',
          'Docker Concepts',
          'Container Orchestration',
          'Kubernetes Concepts',
          'Autoscaling',
          'Horizontal Scaling',
          'Serverless Architecture',
          'Background Workers',
          'Job Queues',
          'Task Scheduling',
          'Thread Pools',
          'Service Discovery',
          'Health Checks',
          'Circuit Breakers',
          'Retry Strategies',
          'Timeout Handling',
          'Graceful Degradation',
          'Blue-Green Deployment',
          'Canary Deployment',
          'Rolling Deployment',
          'Multi-Region Compute'
        ]
      },
      {
        nodeId: 'sd-distributed',
        title: 'Distributed Systems',
        description: 'Consensus protocols, Raft, event streaming with Kafka, distributed locking, CQRS, event sourcing, and observability pillars.',
        xpRequired: 400,
        position: { x: 250, y: 250 },
        connections: ['sd-interview', 'sd-cloud'],
        tier: 3,
        topics: [
          'Distributed Systems Fundamentals',
          'CAP Theorem Deep Dive',
          'Consistency Models',
          'Strong Consistency',
          'Eventual Consistency',
          'Causal Consistency',
          'Distributed Transactions',
          'Two-Phase Commit',
          'Distributed Locks',
          'Leader Election',
          'Consensus',
          'Raft',
          'Quorum',
          'Replication Strategies',
          'Partitioning',
          'Consistent Hashing',
          'Gossip Protocol',
          'Message Queues',
          'Event-Driven Architecture',
          'Pub/Sub',
          'Kafka Architecture',
          'Exactly-Once Delivery',
          'At-Least-Once Delivery',
          'At-Most-Once Delivery',
          'Event Ordering',
          'Idempotency',
          'Dead Letter Queues',
          'Stream Processing',
          'Event Sourcing',
          'CQRS',
          'Distributed Scheduling',
          'Distributed Rate Limiting',
          'Distributed Caching',
          'Service Mesh',
          'Observability',
          'Distributed Tracing',
          'Metrics',
          'Logging',
          'Failure Detection',
          'Disaster Recovery',
          'Multi-Region Systems'
        ]
      },
      {
        nodeId: 'sd-interview',
        title: 'Interview Prep',
        description: 'Real-world FAANG interview challenges: URL shorteners, chat systems, feed ranking, video streaming, and ride sharing.',
        xpRequired: 600,
        position: { x: 150, y: 350 },
        connections: ['sd-master'],
        tier: 4,
        topics: [
          'Design URL Shortener',
          'Design Pastebin',
          'Design a Rate Limiter',
          'Design a Notification System',
          'Design a Chat System',
          'Design WhatsApp',
          'Design Telegram',
          'Design Slack',
          'Design Twitter/X',
          'Design Instagram',
          'Design Facebook News Feed',
          'Design LinkedIn',
          'Design YouTube',
          'Design Netflix',
          'Design Spotify',
          'Design Uber',
          'Design Google Maps',
          'Design Food Delivery System',
          'Design Ride Sharing System',
          'Design E-commerce Platform',
          'Design Amazon',
          'Design Payment System',
          'Design Ticket Booking System',
          'Design Hotel Booking System',
          'Design Flight Booking System',
          'Design File Storage System',
          'Design Dropbox',
          'Design Google Drive',
          'Design Search Autocomplete',
          'Design Web Crawler',
          'Design Search Engine',
          'Design Distributed Cache',
          'Design Distributed Queue',
          'Design Logging System',
          'Design Monitoring System'
        ]
      },
      {
        nodeId: 'sd-cloud',
        title: 'Cloud Architecture',
        description: 'Cloud networking (VPCs, subnets), managed services, infrastructure as code, security perimeter, and multi-region patterns.',
        xpRequired: 600,
        position: { x: 350, y: 350 },
        connections: ['sd-master'],
        tier: 4,
        topics: [
          'Cloud Fundamentals',
          'Regions',
          'Availability Zones',
          'VPC / Virtual Networks',
          'Subnets',
          'Public vs Private Networks',
          'DNS',
          'CDN',
          'Load Balancers',
          'API Gateways',
          'Compute Services',
          'Managed Databases',
          'Object Storage',
          'Managed Caches',
          'Message Queues',
          'Event Streaming',
          'Container Platforms',
          'Kubernetes',
          'Serverless',
          'Autoscaling',
          'Infrastructure as Code',
          'Secrets Management',
          'IAM',
          'Encryption',
          'TLS',
          'WAF',
          'DDoS Protection',
          'Monitoring',
          'Logging',
          'Distributed Tracing',
          'Disaster Recovery',
          'Backup Strategies',
          'Multi-AZ Architecture',
          'Multi-Region Architecture',
          'Active-Active Architecture',
          'Active-Passive Architecture',
          'Blue-Green Deployment',
          'Canary Deployment',
          'Cost Optimization',
          'Cloud Security'
        ]
      },
      {
        nodeId: 'sd-master',
        title: 'Architect',
        description: 'Designing for billions of users, global active-active multi-region systems, real-time ad tech, chaos engineering, and zero-trust security.',
        xpRequired: 1000,
        position: { x: 250, y: 450 },
        connections: [],
        tier: 5,
        topics: [
          'Designing for Billions of Users',
          'Global Distributed Systems',
          'Multi-Region Architecture',
          'Active-Active Architecture',
          'Global Traffic Management',
          'Global Load Balancing',
          'Edge Computing',
          'CDN Architecture',
          'Geo-Distributed Databases',
          'Global Data Replication',
          'Conflict Resolution',
          'Distributed Consensus',
          'Large-Scale Event Streaming',
          'Real-Time Systems',
          'Massive Notification Systems',
          'High-Scale Search',
          'Recommendation Systems',
          'Ad Serving Systems',
          'Fraud Detection Systems',
          'Payment Infrastructure',
          'Financial Transaction Systems',
          'Distributed Rate Limiting',
          'Large-Scale Caching',
          'Large-Scale Messaging',
          'Data Pipelines',
          'Stream Processing',
          'Batch Processing',
          'Lambda Architecture',
          'Kappa Architecture',
          'Data Consistency at Scale',
          'Disaster Recovery Architecture',
          'Chaos Engineering',
          'SLO / SLA / SLI',
          'Reliability Engineering',
          'Capacity Planning at Scale',
          'Cost vs Performance Trade-offs',
          'Security Architecture',
          'Zero Trust Architecture',
          'Multi-Tenant Architecture',
          'System Design Trade-offs'
        ]
      },
    ],
  },
];

module.exports = skillTrees;
